name: Build

on:
  push:
    branches:
      - my/*
  pull_request:
    branches:
      - my/*
  workflow_dispatch:
    branches:
      - my/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Build
      run: |
        ./gradlew assembleDebug
    - name: Store generated APK file
      uses: actions/upload-artifact@v3
      with:
        name: termux-boot
        path: ./app/build/outputs/apk/debug/app-debug.apk

  upload:
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Upload APKs to release
        uses: termux/upload-release-action@v4.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "**/*.apk"
          file_glob: true
          release_name: 
          tag: ${{ github.run_number }}-${{ github.run_id }}
          checksums: sha256,sha512,md5
