name: Build and Deploy

on:
  push:
    branches:
      - my/*
  pull_request:
    branches:
      - my/*
  workflow_dispatch:
    branches:
      - my/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Modify app/build.gradle
      run: |
        # Retrieve keystore file from Emacs feature/android branch.
        git clone --depth 1 \
                  --branch feature/android \
                  --no-checkout https://github.com/emacs-mirror/emacs.git
        git -C emacs sparse-checkout set java/emacs.keystore
        git -C emacs checkout feature/android

        # sed app/build.gradle to refer java/emacs.keystore instead of testkey_untrusted.jks.
        perl -pi -e "s|storeFile file\('testkey_untrusted.jks'\)|storeFile file('../emacs/java/emacs.keystore')|;s|keyAlias 'alias'|keyAlias 'emacs keystore'|;s|storePassword 'xrj45yWGLbsO7W0v'|storePassword 'emacs1'|;s|keyPassword 'xrj45yWGLbsO7W0v'|keyPassword 'emacs1'|" app/build.gradle
    - name: Build
      run: |
        ./gradlew assembleDebug
    - name: Store generated APK file
      uses: actions/upload-artifact@v3
      with:
        name: termux-boot
        path: ./app/build/outputs/apk/debug/app-debug.apk

  upload:
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Upload APKs to release
        uses: termux/upload-release-action@v4.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "**/*.apk"
          file_glob: true
          release_name: 
          tag: ${{ github.run_number }}-${{ github.run_id }}
          checksums: sha256,sha512,md5
